@rem 512k cart for Coleco

d:\work\setbinsize\release\setbinsize tf3.rom 16384

copy /b ..\loaderC.bin ^
+ /b ..\loaderC.bin ^
+ /b ..\loaderC.bin ^
+ /b ..\loaderC.bin ^
+ /b ..\loaderC.bin ^
+ /b ..\loaderC.bin ^
+ /b ..\loaderC.bin ^
+ /b ..\loaderC.bin ^
+ /b ..\TF3TI00.sbf ^
+ /b ..\TF3TI00.sbf ^
+ /b ..\TF3TI01.sbf ^
+ /b ..\TF3TI01.sbf ^
+ /b ..\TF3TI02.sbf ^
+ /b ..\TF3TI02.sbf ^
+ /b ..\TF3TI03.sbf ^
+ /b ..\TF3TI03.sbf ^
+ /b ..\TF3TI04.sbf ^
+ /b ..\TF3TI04.sbf ^
+ /b ..\TF3TI05.sbf ^
+ /b ..\TF3TI05.sbf ^
+ /b ..\TF3TI06.sbf ^
+ /b ..\TF3TI06.sbf ^
+ /b ..\TF3TI07.sbf ^
+ /b ..\TF3TI07.sbf ^
+ /b ..\TF3TI08.sbf ^
+ /b ..\TF3TI08.sbf ^
+ /b ..\TF3TI09.sbf ^
+ /b ..\TF3TI09.sbf ^
+ /b ..\TF3TI10.sbf ^
+ /b ..\TF3TI10.sbf ^
+ /b ..\TF3TI11.sbf ^
+ /b ..\TF3TI11.sbf ^
+ /b ..\map_boss_unknown.bin ^
+ /b ..\map_boss_unknown.bin ^
+ /b ..\map_bosscerberus.bin ^
+ /b ..\map_bosscerberus.bin ^
+ /b ..\map_bossfish.bin ^
+ /b ..\map_bossfish.bin ^
+ /b ..\map_bossfort.bin ^
+ /b ..\map_bossfort.bin ^
+ /b ..\map_bossgargoyle.bin ^
+ /b ..\map_bossgargoyle.bin ^
+ /b ..\map_bosslobster.bin ^
+ /b ..\map_bosslobster.bin ^
+ /b ..\map_bossvulcan.bin ^
+ /b ..\map_bossvulcan.bin ^
+ /b ..\map_briefing.bin ^
+ /b ..\map_briefing.bin ^
+ /b ..\map_briefingornbase.bin ^
+ /b ..\map_briefingornbase.bin ^
+ /b ..\map_titleThird1.bin ^
+ /b ..\map_titleThird1.bin ^
+ /b ..\map_titleThird2.bin ^
+ /b ..\map_titleThird2.bin ^
+ /b ..\map_titleThird3.bin ^
+ /b ..\map_titleThird3.bin ^
+ /b ..\TF3TI12.sbf ^
+ /b ..\TF3TI12.sbf ^
+ /b ..\TF3TI13.sbf ^
+ /b ..\TF3TI13.sbf ^
+ /b ..\TF3TI14.sbf ^
+ /b ..\TF3TI14.sbf ^
+ /b TF3.rom ^
TF3_Coleco.ROM

